export default [
  {
    login: "Magicianred",
    id: 4624113,
    node_id: "MDQ6VXNlcjQ2MjQxMTM=",
    avatar_url: "https://avatars.githubusercontent.com/u/4624113?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Magicianred",
    html_url: "https://github.com/Magicianred",
    followers_url: "https://api.github.com/users/Magicianred/followers",
    following_url:
      "https://api.github.com/users/Magicianred/following{/other_user}",
    gists_url: "https://api.github.com/users/Magicianred/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Magicianred/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Magicianred/subscriptions",
    organizations_url: "https://api.github.com/users/Magicianred/orgs",
    repos_url: "https://api.github.com/users/Magicianred/repos",
    events_url: "https://api.github.com/users/Magicianred/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Magicianred/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "aydgn",
    id: 6154224,
    node_id: "MDQ6VXNlcjYxNTQyMjQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/6154224?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aydgn",
    html_url: "https://github.com/aydgn",
    followers_url: "https://api.github.com/users/aydgn/followers",
    following_url: "https://api.github.com/users/aydgn/following{/other_user}",
    gists_url: "https://api.github.com/users/aydgn/gists{/gist_id}",
    starred_url: "https://api.github.com/users/aydgn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aydgn/subscriptions",
    organizations_url: "https://api.github.com/users/aydgn/orgs",
    repos_url: "https://api.github.com/users/aydgn/repos",
    events_url: "https://api.github.com/users/aydgn/events{/privacy}",
    received_events_url: "https://api.github.com/users/aydgn/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ihanadi",
    id: 32931398,
    node_id: "MDQ6VXNlcjMyOTMxMzk4",
    avatar_url: "https://avatars.githubusercontent.com/u/32931398?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ihanadi",
    html_url: "https://github.com/ihanadi",
    followers_url: "https://api.github.com/users/ihanadi/followers",
    following_url:
      "https://api.github.com/users/ihanadi/following{/other_user}",
    gists_url: "https://api.github.com/users/ihanadi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ihanadi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ihanadi/subscriptions",
    organizations_url: "https://api.github.com/users/ihanadi/orgs",
    repos_url: "https://api.github.com/users/ihanadi/repos",
    events_url: "https://api.github.com/users/ihanadi/events{/privacy}",
    received_events_url: "https://api.github.com/users/ihanadi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alperenArikan",
    id: 38817185,
    node_id: "MDQ6VXNlcjM4ODE3MTg1",
    avatar_url: "https://avatars.githubusercontent.com/u/38817185?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alperenArikan",
    html_url: "https://github.com/alperenArikan",
    followers_url: "https://api.github.com/users/alperenArikan/followers",
    following_url:
      "https://api.github.com/users/alperenArikan/following{/other_user}",
    gists_url: "https://api.github.com/users/alperenArikan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alperenArikan/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/alperenArikan/subscriptions",
    organizations_url: "https://api.github.com/users/alperenArikan/orgs",
    repos_url: "https://api.github.com/users/alperenArikan/repos",
    events_url: "https://api.github.com/users/alperenArikan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alperenArikan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ahmedbustani",
    id: 39660643,
    node_id: "MDQ6VXNlcjM5NjYwNjQz",
    avatar_url: "https://avatars.githubusercontent.com/u/39660643?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ahmedbustani",
    html_url: "https://github.com/Ahmedbustani",
    followers_url: "https://api.github.com/users/Ahmedbustani/followers",
    following_url:
      "https://api.github.com/users/Ahmedbustani/following{/other_user}",
    gists_url: "https://api.github.com/users/Ahmedbustani/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Ahmedbustani/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Ahmedbustani/subscriptions",
    organizations_url: "https://api.github.com/users/Ahmedbustani/orgs",
    repos_url: "https://api.github.com/users/Ahmedbustani/repos",
    events_url: "https://api.github.com/users/Ahmedbustani/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Ahmedbustani/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "abdurrahmanseyidoglu",
    id: 40239163,
    node_id: "MDQ6VXNlcjQwMjM5MTYz",
    avatar_url: "https://avatars.githubusercontent.com/u/40239163?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/abdurrahmanseyidoglu",
    html_url: "https://github.com/abdurrahmanseyidoglu",
    followers_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/followers",
    following_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/following{/other_user}",
    gists_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/subscriptions",
    organizations_url: "https://api.github.com/users/abdurrahmanseyidoglu/orgs",
    repos_url: "https://api.github.com/users/abdurrahmanseyidoglu/repos",
    events_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/abdurrahmanseyidoglu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ercumentlacin",
    id: 41874858,
    node_id: "MDQ6VXNlcjQxODc0ODU4",
    avatar_url: "https://avatars.githubusercontent.com/u/41874858?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ercumentlacin",
    html_url: "https://github.com/ercumentlacin",
    followers_url: "https://api.github.com/users/ercumentlacin/followers",
    following_url:
      "https://api.github.com/users/ercumentlacin/following{/other_user}",
    gists_url: "https://api.github.com/users/ercumentlacin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ercumentlacin/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ercumentlacin/subscriptions",
    organizations_url: "https://api.github.com/users/ercumentlacin/orgs",
    repos_url: "https://api.github.com/users/ercumentlacin/repos",
    events_url: "https://api.github.com/users/ercumentlacin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ercumentlacin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mhmmtbilgin",
    id: 45104758,
    node_id: "MDQ6VXNlcjQ1MTA0NzU4",
    avatar_url: "https://avatars.githubusercontent.com/u/45104758?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mhmmtbilgin",
    html_url: "https://github.com/mhmmtbilgin",
    followers_url: "https://api.github.com/users/mhmmtbilgin/followers",
    following_url:
      "https://api.github.com/users/mhmmtbilgin/following{/other_user}",
    gists_url: "https://api.github.com/users/mhmmtbilgin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mhmmtbilgin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mhmmtbilgin/subscriptions",
    organizations_url: "https://api.github.com/users/mhmmtbilgin/orgs",
    repos_url: "https://api.github.com/users/mhmmtbilgin/repos",
    events_url: "https://api.github.com/users/mhmmtbilgin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mhmmtbilgin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "xdvrx1",
    id: 47092464,
    node_id: "MDQ6VXNlcjQ3MDkyNDY0",
    avatar_url: "https://avatars.githubusercontent.com/u/47092464?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xdvrx1",
    html_url: "https://github.com/xdvrx1",
    followers_url: "https://api.github.com/users/xdvrx1/followers",
    following_url: "https://api.github.com/users/xdvrx1/following{/other_user}",
    gists_url: "https://api.github.com/users/xdvrx1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/xdvrx1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xdvrx1/subscriptions",
    organizations_url: "https://api.github.com/users/xdvrx1/orgs",
    repos_url: "https://api.github.com/users/xdvrx1/repos",
    events_url: "https://api.github.com/users/xdvrx1/events{/privacy}",
    received_events_url: "https://api.github.com/users/xdvrx1/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "YusraSenimDede",
    id: 50294199,
    node_id: "MDQ6VXNlcjUwMjk0MTk5",
    avatar_url: "https://avatars.githubusercontent.com/u/50294199?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/YusraSenimDede",
    html_url: "https://github.com/YusraSenimDede",
    followers_url: "https://api.github.com/users/YusraSenimDede/followers",
    following_url:
      "https://api.github.com/users/YusraSenimDede/following{/other_user}",
    gists_url: "https://api.github.com/users/YusraSenimDede/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/YusraSenimDede/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/YusraSenimDede/subscriptions",
    organizations_url: "https://api.github.com/users/YusraSenimDede/orgs",
    repos_url: "https://api.github.com/users/YusraSenimDede/repos",
    events_url: "https://api.github.com/users/YusraSenimDede/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/YusraSenimDede/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "delfinozturk",
    id: 52176295,
    node_id: "MDQ6VXNlcjUyMTc2Mjk1",
    avatar_url: "https://avatars.githubusercontent.com/u/52176295?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/delfinozturk",
    html_url: "https://github.com/delfinozturk",
    followers_url: "https://api.github.com/users/delfinozturk/followers",
    following_url:
      "https://api.github.com/users/delfinozturk/following{/other_user}",
    gists_url: "https://api.github.com/users/delfinozturk/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/delfinozturk/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/delfinozturk/subscriptions",
    organizations_url: "https://api.github.com/users/delfinozturk/orgs",
    repos_url: "https://api.github.com/users/delfinozturk/repos",
    events_url: "https://api.github.com/users/delfinozturk/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/delfinozturk/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "baristunar",
    id: 58105650,
    node_id: "MDQ6VXNlcjU4MTA1NjUw",
    avatar_url: "https://avatars.githubusercontent.com/u/58105650?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/baristunar",
    html_url: "https://github.com/baristunar",
    followers_url: "https://api.github.com/users/baristunar/followers",
    following_url:
      "https://api.github.com/users/baristunar/following{/other_user}",
    gists_url: "https://api.github.com/users/baristunar/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/baristunar/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/baristunar/subscriptions",
    organizations_url: "https://api.github.com/users/baristunar/orgs",
    repos_url: "https://api.github.com/users/baristunar/repos",
    events_url: "https://api.github.com/users/baristunar/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/baristunar/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Semra4141",
    id: 60344956,
    node_id: "MDQ6VXNlcjYwMzQ0OTU2",
    avatar_url: "https://avatars.githubusercontent.com/u/60344956?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Semra4141",
    html_url: "https://github.com/Semra4141",
    followers_url: "https://api.github.com/users/Semra4141/followers",
    following_url:
      "https://api.github.com/users/Semra4141/following{/other_user}",
    gists_url: "https://api.github.com/users/Semra4141/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Semra4141/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Semra4141/subscriptions",
    organizations_url: "https://api.github.com/users/Semra4141/orgs",
    repos_url: "https://api.github.com/users/Semra4141/repos",
    events_url: "https://api.github.com/users/Semra4141/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Semra4141/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "devcihat",
    id: 61031932,
    node_id: "MDQ6VXNlcjYxMDMxOTMy",
    avatar_url: "https://avatars.githubusercontent.com/u/61031932?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/devcihat",
    html_url: "https://github.com/devcihat",
    followers_url: "https://api.github.com/users/devcihat/followers",
    following_url:
      "https://api.github.com/users/devcihat/following{/other_user}",
    gists_url: "https://api.github.com/users/devcihat/gists{/gist_id}",
    starred_url: "https://api.github.com/users/devcihat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/devcihat/subscriptions",
    organizations_url: "https://api.github.com/users/devcihat/orgs",
    repos_url: "https://api.github.com/users/devcihat/repos",
    events_url: "https://api.github.com/users/devcihat/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/devcihat/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mertssmnoglu",
    id: 61623638,
    node_id: "MDQ6VXNlcjYxNjIzNjM4",
    avatar_url: "https://avatars.githubusercontent.com/u/61623638?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mertssmnoglu",
    html_url: "https://github.com/mertssmnoglu",
    followers_url: "https://api.github.com/users/mertssmnoglu/followers",
    following_url:
      "https://api.github.com/users/mertssmnoglu/following{/other_user}",
    gists_url: "https://api.github.com/users/mertssmnoglu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mertssmnoglu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/mertssmnoglu/subscriptions",
    organizations_url: "https://api.github.com/users/mertssmnoglu/orgs",
    repos_url: "https://api.github.com/users/mertssmnoglu/repos",
    events_url: "https://api.github.com/users/mertssmnoglu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mertssmnoglu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sennurcoban",
    id: 62256886,
    node_id: "MDQ6VXNlcjYyMjU2ODg2",
    avatar_url: "https://avatars.githubusercontent.com/u/62256886?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sennurcoban",
    html_url: "https://github.com/sennurcoban",
    followers_url: "https://api.github.com/users/sennurcoban/followers",
    following_url:
      "https://api.github.com/users/sennurcoban/following{/other_user}",
    gists_url: "https://api.github.com/users/sennurcoban/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sennurcoban/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sennurcoban/subscriptions",
    organizations_url: "https://api.github.com/users/sennurcoban/orgs",
    repos_url: "https://api.github.com/users/sennurcoban/repos",
    events_url: "https://api.github.com/users/sennurcoban/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sennurcoban/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "keremkaradenzz",
    id: 64808302,
    node_id: "MDQ6VXNlcjY0ODA4MzAy",
    avatar_url: "https://avatars.githubusercontent.com/u/64808302?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/keremkaradenzz",
    html_url: "https://github.com/keremkaradenzz",
    followers_url: "https://api.github.com/users/keremkaradenzz/followers",
    following_url:
      "https://api.github.com/users/keremkaradenzz/following{/other_user}",
    gists_url: "https://api.github.com/users/keremkaradenzz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/keremkaradenzz/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/keremkaradenzz/subscriptions",
    organizations_url: "https://api.github.com/users/keremkaradenzz/orgs",
    repos_url: "https://api.github.com/users/keremkaradenzz/repos",
    events_url: "https://api.github.com/users/keremkaradenzz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/keremkaradenzz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mail-aizhan",
    id: 65739091,
    node_id: "MDQ6VXNlcjY1NzM5MDkx",
    avatar_url: "https://avatars.githubusercontent.com/u/65739091?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mail-aizhan",
    html_url: "https://github.com/mail-aizhan",
    followers_url: "https://api.github.com/users/mail-aizhan/followers",
    following_url:
      "https://api.github.com/users/mail-aizhan/following{/other_user}",
    gists_url: "https://api.github.com/users/mail-aizhan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mail-aizhan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mail-aizhan/subscriptions",
    organizations_url: "https://api.github.com/users/mail-aizhan/orgs",
    repos_url: "https://api.github.com/users/mail-aizhan/repos",
    events_url: "https://api.github.com/users/mail-aizhan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mail-aizhan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "serkanc7",
    id: 65915453,
    node_id: "MDQ6VXNlcjY1OTE1NDUz",
    avatar_url: "https://avatars.githubusercontent.com/u/65915453?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/serkanc7",
    html_url: "https://github.com/serkanc7",
    followers_url: "https://api.github.com/users/serkanc7/followers",
    following_url:
      "https://api.github.com/users/serkanc7/following{/other_user}",
    gists_url: "https://api.github.com/users/serkanc7/gists{/gist_id}",
    starred_url: "https://api.github.com/users/serkanc7/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/serkanc7/subscriptions",
    organizations_url: "https://api.github.com/users/serkanc7/orgs",
    repos_url: "https://api.github.com/users/serkanc7/repos",
    events_url: "https://api.github.com/users/serkanc7/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/serkanc7/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gizemnkorkmaz",
    id: 66412137,
    node_id: "MDQ6VXNlcjY2NDEyMTM3",
    avatar_url: "https://avatars.githubusercontent.com/u/66412137?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gizemnkorkmaz",
    html_url: "https://github.com/gizemnkorkmaz",
    followers_url: "https://api.github.com/users/gizemnkorkmaz/followers",
    following_url:
      "https://api.github.com/users/gizemnkorkmaz/following{/other_user}",
    gists_url: "https://api.github.com/users/gizemnkorkmaz/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gizemnkorkmaz/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/gizemnkorkmaz/subscriptions",
    organizations_url: "https://api.github.com/users/gizemnkorkmaz/orgs",
    repos_url: "https://api.github.com/users/gizemnkorkmaz/repos",
    events_url: "https://api.github.com/users/gizemnkorkmaz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gizemnkorkmaz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Rinedhajosman",
    id: 66697143,
    node_id: "MDQ6VXNlcjY2Njk3MTQz",
    avatar_url: "https://avatars.githubusercontent.com/u/66697143?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Rinedhajosman",
    html_url: "https://github.com/Rinedhajosman",
    followers_url: "https://api.github.com/users/Rinedhajosman/followers",
    following_url:
      "https://api.github.com/users/Rinedhajosman/following{/other_user}",
    gists_url: "https://api.github.com/users/Rinedhajosman/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Rinedhajosman/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Rinedhajosman/subscriptions",
    organizations_url: "https://api.github.com/users/Rinedhajosman/orgs",
    repos_url: "https://api.github.com/users/Rinedhajosman/repos",
    events_url: "https://api.github.com/users/Rinedhajosman/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Rinedhajosman/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nurgeldiatamyradov",
    id: 67277491,
    node_id: "MDQ6VXNlcjY3Mjc3NDkx",
    avatar_url: "https://avatars.githubusercontent.com/u/67277491?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nurgeldiatamyradov",
    html_url: "https://github.com/nurgeldiatamyradov",
    followers_url: "https://api.github.com/users/nurgeldiatamyradov/followers",
    following_url:
      "https://api.github.com/users/nurgeldiatamyradov/following{/other_user}",
    gists_url:
      "https://api.github.com/users/nurgeldiatamyradov/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/nurgeldiatamyradov/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/nurgeldiatamyradov/subscriptions",
    organizations_url: "https://api.github.com/users/nurgeldiatamyradov/orgs",
    repos_url: "https://api.github.com/users/nurgeldiatamyradov/repos",
    events_url:
      "https://api.github.com/users/nurgeldiatamyradov/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nurgeldiatamyradov/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hackerd2020",
    id: 67505023,
    node_id: "MDQ6VXNlcjY3NTA1MDIz",
    avatar_url: "https://avatars.githubusercontent.com/u/67505023?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hackerd2020",
    html_url: "https://github.com/hackerd2020",
    followers_url: "https://api.github.com/users/hackerd2020/followers",
    following_url:
      "https://api.github.com/users/hackerd2020/following{/other_user}",
    gists_url: "https://api.github.com/users/hackerd2020/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hackerd2020/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hackerd2020/subscriptions",
    organizations_url: "https://api.github.com/users/hackerd2020/orgs",
    repos_url: "https://api.github.com/users/hackerd2020/repos",
    events_url: "https://api.github.com/users/hackerd2020/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hackerd2020/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nepesovparahat",
    id: 67821216,
    node_id: "MDQ6VXNlcjY3ODIxMjE2",
    avatar_url: "https://avatars.githubusercontent.com/u/67821216?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nepesovparahat",
    html_url: "https://github.com/nepesovparahat",
    followers_url: "https://api.github.com/users/nepesovparahat/followers",
    following_url:
      "https://api.github.com/users/nepesovparahat/following{/other_user}",
    gists_url: "https://api.github.com/users/nepesovparahat/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/nepesovparahat/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/nepesovparahat/subscriptions",
    organizations_url: "https://api.github.com/users/nepesovparahat/orgs",
    repos_url: "https://api.github.com/users/nepesovparahat/repos",
    events_url: "https://api.github.com/users/nepesovparahat/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nepesovparahat/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hasan-alkhalaf",
    id: 69852321,
    node_id: "MDQ6VXNlcjY5ODUyMzIx",
    avatar_url: "https://avatars.githubusercontent.com/u/69852321?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hasan-alkhalaf",
    html_url: "https://github.com/hasan-alkhalaf",
    followers_url: "https://api.github.com/users/hasan-alkhalaf/followers",
    following_url:
      "https://api.github.com/users/hasan-alkhalaf/following{/other_user}",
    gists_url: "https://api.github.com/users/hasan-alkhalaf/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hasan-alkhalaf/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/hasan-alkhalaf/subscriptions",
    organizations_url: "https://api.github.com/users/hasan-alkhalaf/orgs",
    repos_url: "https://api.github.com/users/hasan-alkhalaf/repos",
    events_url: "https://api.github.com/users/hasan-alkhalaf/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hasan-alkhalaf/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "fatihgvnc",
    id: 70134562,
    node_id: "MDQ6VXNlcjcwMTM0NTYy",
    avatar_url: "https://avatars.githubusercontent.com/u/70134562?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/fatihgvnc",
    html_url: "https://github.com/fatihgvnc",
    followers_url: "https://api.github.com/users/fatihgvnc/followers",
    following_url:
      "https://api.github.com/users/fatihgvnc/following{/other_user}",
    gists_url: "https://api.github.com/users/fatihgvnc/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/fatihgvnc/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/fatihgvnc/subscriptions",
    organizations_url: "https://api.github.com/users/fatihgvnc/orgs",
    repos_url: "https://api.github.com/users/fatihgvnc/repos",
    events_url: "https://api.github.com/users/fatihgvnc/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/fatihgvnc/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "FatmaSehitoglu",
    id: 71012407,
    node_id: "MDQ6VXNlcjcxMDEyNDA3",
    avatar_url: "https://avatars.githubusercontent.com/u/71012407?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/FatmaSehitoglu",
    html_url: "https://github.com/FatmaSehitoglu",
    followers_url: "https://api.github.com/users/FatmaSehitoglu/followers",
    following_url:
      "https://api.github.com/users/FatmaSehitoglu/following{/other_user}",
    gists_url: "https://api.github.com/users/FatmaSehitoglu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/FatmaSehitoglu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/FatmaSehitoglu/subscriptions",
    organizations_url: "https://api.github.com/users/FatmaSehitoglu/orgs",
    repos_url: "https://api.github.com/users/FatmaSehitoglu/repos",
    events_url: "https://api.github.com/users/FatmaSehitoglu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/FatmaSehitoglu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "akadiraslan",
    id: 71260913,
    node_id: "MDQ6VXNlcjcxMjYwOTEz",
    avatar_url: "https://avatars.githubusercontent.com/u/71260913?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/akadiraslan",
    html_url: "https://github.com/akadiraslan",
    followers_url: "https://api.github.com/users/akadiraslan/followers",
    following_url:
      "https://api.github.com/users/akadiraslan/following{/other_user}",
    gists_url: "https://api.github.com/users/akadiraslan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/akadiraslan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/akadiraslan/subscriptions",
    organizations_url: "https://api.github.com/users/akadiraslan/orgs",
    repos_url: "https://api.github.com/users/akadiraslan/repos",
    events_url: "https://api.github.com/users/akadiraslan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/akadiraslan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Haticesurumlu",
    id: 71832100,
    node_id: "MDQ6VXNlcjcxODMyMTAw",
    avatar_url: "https://avatars.githubusercontent.com/u/71832100?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Haticesurumlu",
    html_url: "https://github.com/Haticesurumlu",
    followers_url: "https://api.github.com/users/Haticesurumlu/followers",
    following_url:
      "https://api.github.com/users/Haticesurumlu/following{/other_user}",
    gists_url: "https://api.github.com/users/Haticesurumlu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Haticesurumlu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Haticesurumlu/subscriptions",
    organizations_url: "https://api.github.com/users/Haticesurumlu/orgs",
    repos_url: "https://api.github.com/users/Haticesurumlu/repos",
    events_url: "https://api.github.com/users/Haticesurumlu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Haticesurumlu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mervesahinmerve",
    id: 72298655,
    node_id: "MDQ6VXNlcjcyMjk4NjU1",
    avatar_url: "https://avatars.githubusercontent.com/u/72298655?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mervesahinmerve",
    html_url: "https://github.com/mervesahinmerve",
    followers_url: "https://api.github.com/users/mervesahinmerve/followers",
    following_url:
      "https://api.github.com/users/mervesahinmerve/following{/other_user}",
    gists_url: "https://api.github.com/users/mervesahinmerve/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mervesahinmerve/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/mervesahinmerve/subscriptions",
    organizations_url: "https://api.github.com/users/mervesahinmerve/orgs",
    repos_url: "https://api.github.com/users/mervesahinmerve/repos",
    events_url: "https://api.github.com/users/mervesahinmerve/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mervesahinmerve/received_events",
    type: "User",
    site_admin: false,
  },
];
