export default {
  login: "BurakCaglar",
  id: 61995612,
  node_id: "MDQ6VXNlcjYxOTk1NjEy",
  avatar_url: "https://avatars.githubusercontent.com/u/61995612?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/BurakCaglar",
  html_url: "https://github.com/BurakCaglar",
  followers_url: "https://api.github.com/users/BurakCaglar/followers",
  following_url:
    "https://api.github.com/users/BurakCaglar/following{/other_user}",
  gists_url: "https://api.github.com/users/BurakCaglar/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/BurakCaglar/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/BurakCaglar/subscriptions",
  organizations_url: "https://api.github.com/users/BurakCaglar/orgs",
  repos_url: "https://api.github.com/users/BurakCaglar/repos",
  events_url: "https://api.github.com/users/BurakCaglar/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/BurakCaglar/received_events",
  type: "User",
  site_admin: false,
  name: "Burak Caglar",
  company: null,
  blog: "",
  location: "Istanbul, Turkey",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 24,
  public_gists: 0,
  followers: 45,
  following: 53,
  created_at: "2020-03-09T23:05:38Z",
  updated_at: "2021-07-10T19:23:52Z",
};
